# Generated by Django 3.0.3 on 2021-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('NO_FILTER', 'no filter'), ('HSV', 'hsv'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ajax_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
