# Generated by Django 4.2.8 on 2024-02-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ajax_Filters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveImageModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="ajax_images")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
