# Generated by Django 4.2.8 on 2024-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ajax_Filters", "0002_saveimagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveimagemodel",
            name="image",
            field=models.ImageField(upload_to="pacoca_air"),
        ),
    ]
